### ISSUE TITLE
Nullscape Compatibility

### ISSUE THREAD

**Issue by Fyoncle** [The-Architects727/BetterEndCitiesVanilla#1]
![image](https://github.com/The-Architects727/BetterEndCitiesVanilla/assets/63975256/767e26ed-a9e7-4133-abe3-88ce1d0a4e92)
Nullscape compat?

**Comment by The-Architects727** [comment]
Ok. This datapack only changes the look of the end cities. I am pretty sure that these same issues would be present even if you did not use my datapack. 
if you make a new world with the same seed, but without the pack and the city generates correctly, then please tell me. 

Basically what is happening is that it starts by generating on a block down below and then it just grows upward through the blocks. There is not really much I can do to change that.

**Comment by Fyoncle** [comment]
> Ok. This datapack only changes the look of the end cities. I am pretty sure that these same issues would be present even if you did not use my datapack. if you make a new world with the same seed, but without the pack and the city generates correctly, then please tell me.
> 
> Basically what is happening is that it starts by generating on a block down below and then it just grows upward through the blocks. There is not really much I can do to change that.

Nope same shouldn't happen with the Nullscape generation.

**Comment by Fyoncle** [comment]
Wait im sorry, it also happens with default but, does it have any known issues with Nullscape?

**Comment by The-Architects727** [comment]
> Wait im sorry, it also happens with default but, does it have any known issues with Nullscape?

Not that i know of. Again this just changes the look of the structures, not the actual generation. Though it would depend on the version of Nullscape, because i know that in earlier versions of Nullscape, the end dimension is replaced, but i know that in newer versions that was changed and not has much more compatibility.

**Comment by Fyoncle** [comment]
> > Wait im sorry, it also happens with default but, does it have any known issues with Nullscape?
> 
> Not that i know of. Again this just changes the look of the structures, not the actual generation. Though it would depend on the version of Nullscape, because i know that in earlier versions of Nullscape, the end dimension is replaced, but i know that in newer versions that was changed and not has much more compatibility.

I mean in the latest version of Nullscape on 1.20.1 fabric is having weird generation issues with end citys like spawning inside a whole rock LOL
